services:
  - type: web
    name: vaaniai
    runtime: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
